Repository marian13/convenient_service, pull requests merged in 2022-12, with the labels that each got.

#28 CS-17: Change `delegate_to` default behaviour from `exactly once` to `at least once`
  lib/convenient_service/rspec/matchers/custom/cache_its_value.rb
  lib/convenient_service/rspec/matchers/custom/delegate_to.rb
  spec/lib/convenient_service/rspec/matchers/custom/delegate_to_spec.rb
Labels: feature

#33 CS-21: Fix status on step
  lib/convenient_service/service/plugins/has_result/entities/result/plugins/has_jsend_status_and_attributes/concern/instance_methods.rb
  lib/convenient_service/service/plugins/has_result_steps/middleware.rb
  spec/lib/convenient_service/service/plugins/has_result/entities/result/plugins/has_jsend_status_and_attributes/concern/instance_methods_spec.rb
  spec/lib/convenient_service/service/plugins/has_result_steps/middleware_spec.rb
Labels: fix

#35 CS-22: Fix skipped validations for services with steps
  .github/workflows/ci.yml
  Taskfile.yml
  env.rb
  lib/convenient_service/examples/dry/gemfile/dry_service/config.rb
  lib/convenient_service/examples/dry/gemfile/services/assert_file_exists.rb
  lib/convenient_service/examples/dry/gemfile/services/assert_file_not_empty.rb
  lib/convenient_service/examples/dry/gemfile/services/assert_npm_package_available.rb
  lib/convenient_service/examples/dry/gemfile/services/parse_content.rb
  lib/convenient_service/examples/dry/gemfile/services/print_shell_command.rb
  lib/convenient_service/examples/dry/gemfile/services/read_file_content.rb
  lib/convenient_service/examples/dry/gemfile/services/run_shell.rb
  lib/convenient_service/examples/dry/gemfile/services/strip_comments.rb
  lib/convenient_service/examples/rails/gemfile/rails_service/config.rb
  lib/convenient_service/service/plugins/has_result_params_validations/using_dry_validation/middleware.rb
  spec/lib/convenient_service/examples/dry/gemfile/dry_service/config_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/assert_file_exists_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/assert_file_not_empty_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/assert_npm_package_available_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/parse_content_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/print_shell_command_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/read_file_content_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/run_shell_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/strip_comments_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/rails_service/config_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/assert_file_exists_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/assert_file_not_empty_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/assert_npm_package_available_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/parse_content_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/print_shell_command_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/read_file_content_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/run_shell_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/strip_comments_spec.rb
  spec/lib/convenient_service/service/plugins/has_result_params_validations/using_dry_validation/middleware_spec.rb
Labels: fix

#36 CS-23: Suppress validates specs for Ruby 3 and Rails 5
  lib/convenient_service/dependencies.rb
  lib/convenient_service/dependencies/built_in.rb
  lib/convenient_service/examples/rails/gemfile/services/assert_file_exists.rb
  lib/convenient_service/examples/rails/gemfile/services/assert_file_not_empty.rb
  lib/convenient_service/examples/rails/gemfile/services/assert_npm_package_available.rb
  lib/convenient_service/examples/rails/gemfile/services/parse_content.rb
  lib/convenient_service/examples/rails/gemfile/services/print_shell_command.rb
  lib/convenient_service/examples/rails/gemfile/services/read_file_content.rb
  lib/convenient_service/examples/rails/gemfile/services/run_shell.rb
  lib/convenient_service/examples/rails/gemfile/services/strip_comments.rb
  lib/convenient_service/support.rb
  lib/convenient_service/support/gems.rb
  lib/convenient_service/support/gems/active_model.rb
  lib/convenient_service/support/gems/rspec.rb
  lib/convenient_service/support/ruby.rb
  lib/convenient_service/support/version.rb
  lib/convenient_service/support/version/null_version.rb
  spec/lib/convenient_service/dependencies_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/services/read_file_content_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/assert_file_exists_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/assert_file_not_empty_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/assert_npm_package_available_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/parse_content_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/print_shell_command_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/read_file_content_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/run_shell_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/services/strip_comments_spec.rb
  spec/lib/convenient_service/examples/standard/gemfile/services/read_file_content_spec.rb
  spec/lib/convenient_service/support/gems/active_model_spec.rb
  spec/lib/convenient_service/support/gems/rspec_spec.rb
  spec/lib/convenient_service/support/ruby_spec.rb
  spec/lib/convenient_service/support/version/null_version_spec.rb
  spec/lib/convenient_service/support/version_spec.rb
Labels: suppress

#31 CS-19: `stub_service` without RSpec mocks
  ROADMAP.md
  lib/convenient_service/configs/standard.rb
  lib/convenient_service/dependencies.rb
  lib/convenient_service/rspec/helpers/custom/stub_service/entities/result_spec.rb
  lib/convenient_service/rspec/helpers/custom/stub_service/entities/stubbed_service.rb
  lib/convenient_service/service/plugins.rb
  lib/convenient_service/service/plugins/can_have_stubbed_result.rb
  lib/convenient_service/service/plugins/can_have_stubbed_result/concern.rb
  lib/convenient_service/service/plugins/can_have_stubbed_result/middleware.rb
  lib/convenient_service/support/cache.rb
  lib/convenient_service/utils/object.rb
  lib/convenient_service/utils/object/instance_variable_fetch.rb
  spec/lib/convenient_service/configs/standard_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/dry_service/config_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/rails_service/config_spec.rb
  spec/lib/convenient_service/rspec/helpers/custom/stub_service/entities/result_spec_spec.rb
  spec/lib/convenient_service/rspec/helpers/custom/stub_service/entities/stubbed_service_spec.rb
  spec/lib/convenient_service/service/plugins/can_have_stubbed_result/concern_spec.rb
  spec/lib/convenient_service/service/plugins/can_have_stubbed_result/middleware_spec.rb
  spec/lib/convenient_service/support/cache_spec.rb
  spec/lib/convenient_service/utils/object/instance_variable_fetch_spec.rb
  spec/lib/convenient_service/utils/object_spec.rb
Labels: refactor

#38 CS-24: Fix `can_have_stubbed_result` when it's called in NON-TEST environment
  lib/convenient_service/service/plugins/can_have_stubbed_result/concern.rb
  lib/convenient_service/support/gems/rspec.rb
  spec/lib/convenient_service/service/plugins/can_have_stubbed_result/concern_spec.rb
  spec/lib/convenient_service/support/gems/rspec_spec.rb
Labels: fix

#40 CS-25: A better message for typo in step out methods
  lib/convenient_service/service/plugins/has_result/entities/result/plugins/has_jsend_status_and_attributes/entities/data.rb
  lib/convenient_service/service/plugins/has_result_steps/entities/method/commands/define_method_in_container.rb
  lib/convenient_service/service/plugins/has_result_steps/entities/method/errors.rb
  lib/convenient_service/service/plugins/has_result_steps/entities/step/concern/instance_methods.rb
  spec/lib/convenient_service/service/plugins/has_result/entities/result/plugins/has_jsend_status_and_attributes/entities/data_spec.rb
  spec/lib/convenient_service/service/plugins/has_result_steps/entities/method/commands/define_method_in_container_spec.rb
  spec/lib/convenient_service/service/plugins/has_result_steps/entities/step/concern/instance_methods_spec.rb
Labels: better user experience

#42 CS-26: RSpec.current_example does NOT exist when RSpec is partially loaded
  lib/convenient_service/support/gems/rspec.rb
  spec/lib/convenient_service/service/plugins/can_have_stubbed_result/concern_spec.rb
  spec/lib/convenient_service/support/gems/rspec_spec.rb
Labels: fix
