Repository marian13/convenient_service, pull requests merged in 2023-01, with the labels that each got.

#45 CS-29: Introduce Dependency Containers
  lib/convenient_service.rb
  lib/convenient_service/aliases.rb
  lib/convenient_service/support.rb
  lib/convenient_service/support/dependency_container.rb
  lib/convenient_service/support/dependency_container/commands.rb
  lib/convenient_service/support/dependency_container/commands/create_methods_module.rb
  lib/convenient_service/support/dependency_container/commands/import_method.rb
  lib/convenient_service/support/dependency_container/constants.rb
  lib/convenient_service/support/dependency_container/entities.rb
  lib/convenient_service/support/dependency_container/entities/method.rb
  lib/convenient_service/support/dependency_container/entities/method_collection.rb
  lib/convenient_service/support/dependency_container/entities/namespace.rb
  lib/convenient_service/support/dependency_container/entities/namespace_collection.rb
  lib/convenient_service/support/dependency_container/errors.rb
  lib/convenient_service/support/dependency_container/export.rb
  lib/convenient_service/support/dependency_container/import.rb
  lib/convenient_service/support/not_passed.rb
  lib/convenient_service/utils/module.rb
  lib/convenient_service/utils/module/fetch_own_const.rb
  lib/convenient_service/utils/module/include_module.rb
  lib/convenient_service/utils/proc/conjunct.rb
  lib/convenient_service/utils/string.rb
  lib/convenient_service/utils/string/split.rb
  spec/lib/convenient_service/aliases_spec.rb
  spec/lib/convenient_service/support/dependency_container/constants_spec.rb
  spec/lib/convenient_service/support/dependency_container/entities/method_collection_spec.rb
  spec/lib/convenient_service/support/dependency_container/entities/method_spec.rb
  spec/lib/convenient_service/support/dependency_container/entities/namespace_collection_spec.rb
  spec/lib/convenient_service/support/dependency_container/entities/namespace_spec.rb
  spec/lib/convenient_service/support/dependency_container/export_spec.rb
  spec/lib/convenient_service/support/dependency_container/import_spec.rb
  spec/lib/convenient_service/support/not_passed_spec.rb
  spec/lib/convenient_service/utils/module/fetch_own_const_spec.rb
  spec/lib/convenient_service/utils/module/include_module_spec.rb
  spec/lib/convenient_service/utils/module_spec.rb
  spec/lib/convenient_service/utils/proc/conjunct_spec.rb
Labels: feature

#46 CS-30: Replace `self.included` with `included`
  lib/convenient_service/aliases.rb
  lib/convenient_service/examples/dry/gemfile/dry_service/config.rb
  lib/convenient_service/examples/rails/gemfile/rails_service/config.rb
  spec/lib/convenient_service/aliases_spec.rb
  spec/lib/convenient_service/examples/dry/gemfile/dry_service/config_spec.rb
  spec/lib/convenient_service/examples/rails/gemfile/rails_service/config_spec.rb
Labels: fix

#49 CS-22: Welcome to 2023
  LICENSE.txt
  README.md
Labels: docs

#52 CS-32: Fix typo in `dependency_container`
  lib/convenient_service/support/dependency_container/errors.rb
  spec/lib/convenient_service/support/dependency_container/import_spec.rb
Labels: fix
