Repository marian13/convenient_service, pull requests merged in 2023-02, with the labels that each got.

#56 CS-35: Fix typo in `be_direct_descendant_of` and `be_descendant_of`
  convenient_service.gemspec
  lib/convenient_service/rspec/matchers/custom/be_descendant_of.rb
  lib/convenient_service/rspec/matchers/custom/be_direct_descendant_of.rb
Labels: fix

#58 CS-Y: Logo redesign
  logo.png
Labels: chore

#66 Introduce RescuesResultUnhandledExceptions plugin
  lib/convenient_service/dependencies.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/commands.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/commands/format_backtrace.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/commands/format_cause.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/commands/format_exception.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/commands/format_line.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/constants.rb
  lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/middleware.rb
  spec/lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/commands/format_exception_spec.rb
  spec/lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/commands/format_line_spec.rb
  spec/lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/constants_spec.rb
  spec/lib/convenient_service/service/plugins/rescues_result_unhandled_exceptions/middleware_spec.rb
  spec/support/convenient_service.rb
Labels: feature

#61 CS-37: Implement a logic that forbids to use `export` in classes
  lib/convenient_service/support/dependency_container/errors.rb
  lib/convenient_service/support/dependency_container/export.rb
  spec/lib/convenient_service/support/dependency_container/export_spec.rb
Labels: fix

#68 CS-39: Extract `CanHaveUserProvidedEntity` plugin
  lib/convenient_service/common/plugins.rb
  lib/convenient_service/common/plugins/can_have_user_provided_entity.rb
  lib/convenient_service/common/plugins/can_have_user_provided_entity/commands.rb
  lib/convenient_service/common/plugins/can_have_user_provided_entity/commands/find_or_create_entity.rb
  lib/convenient_service/common/plugins/can_have_user_provided_entity/container.rb
  lib/convenient_service/common/plugins/can_have_user_provided_entity/errors.rb
  lib/convenient_service/common/plugins/has_internals/commands/create_internals_class.rb
  lib/convenient_service/common/plugins/has_internals/concern.rb
  lib/convenient_service/service/plugins/has_result/commands/create_result_class.rb
  lib/convenient_service/service/plugins/has_result/concern/class_methods.rb
  lib/convenient_service/service/plugins/has_result_steps/commands/create_step_class.rb
  spec/lib/convenient_service/common/plugins/can_have_user_provided_entity/commands/find_or_create_entity_spec.rb
  spec/lib/convenient_service/common/plugins/has_internals/commands/create_internals_class_spec.rb
  spec/lib/convenient_service/common/plugins/has_internals/concern_spec.rb
  spec/lib/convenient_service/service/plugins/has_result/commands/create_result_class_spec.rb
  spec/lib/convenient_service/service/plugins/has_result_steps/commands/create_step_class_spec.rb
Labels: refactor
